version: "3.7"

volumes:
    mongo-data:

services:
    app:
        image: extender777/swiper:master
        restart: unless-stopped
        ports:
            - 4000:4000

    db:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db
#Check
