name: Publish Docker image and deploy (both server & client)

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKER_REPO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: server
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_server:
    needs: [push_to_registry]
    name: Deploy to Oracle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: copy file via ssh
        uses: garygrossgarten/github-action-scp@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          local: "server/docker-compose.yml"
          remote: "swiper/docker-compose.yml"

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull latest container
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo docker pull ${{ secrets.DOCKER_REPO }}:master"

      - name: Stop deployed system
        continue-on-error: true
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd swiper && sudo docker-compose down"

      - name: Start system
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd swiper && sudo docker-compose up -d"

  deploy_client:
    name: Build and deploy React app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Set up Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: garygrossgarten/github-action-scp@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          local: "build"
          remote: "/var/www/html"
