name: Publish Docker image

on:
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    REPO: extender777/swiper

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.REPO }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: server
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    deploy:
        needs: [push_to_registry]
        name: Deploy to Oracle
        runs-on: ubuntu-latest
        steps:
            - name: Setup SSH connection
              uses: webfactory/ssh-agent@v0.5.1
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: copy file via ssh password
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "server/docker-compose.yml"
                  target: "~/swiper"

            - name: Pull latest container
              run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo docker pull ${{env.REPO}}:master"

            - name: Stop deployed system
              continue-on-error: true
              run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd swiper && sudo docker-compose down"

            - name: Start system
              run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd swiper && sudo docker-compose up -d"
